name: build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Checkov action
        id: checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12

      - name: Print Result
        run: |
          echo "printing result"
          echo ${{ steps.checkov.outputs.results }}
