name: build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@master
        with:
          api-key: ${{ secrets.BC_API_KEY }}
        env:
          BC_API_URL: ${{ secrets.BC_API_URL }}

      - name: Print Result
        run: |
          echo "printing result"
          echo ${{ steps.checkov.outputs.results }}
